version: '3'
services:

  bash:
    build:
      context: .
    volumes:
       - ka_azumio:/volume
       - ../:/mnt
    entrypoint: "/bin/bash" 
    stdin_open: true
    container_name: "bac_bash_${USER}"
    tty: true
    #user: 1008:1008
    env_file:
      - ../.env 

volumes:
  ka_azumio:
    external:
      true

  # jupyter:
  #   build:
  #     context: .
  #   ports:
  #      - "127.0.0.1::8888"
  #   volumes:
  #      - ../:/mnt
  #   entrypoint: bash -c "cd /mnt && jupyter lab --NotebookApp.token='' --ip=0.0.0.0 --allow-root && /bin/bash" 
  #   #entrypoint: bash -c "cd /ka_azumio && jupyter lab --NotebookApp.token='' --ip=0.0.0.0 --allow-root && /bin/bash" 
  #   stdin_open: true
  #   container_name: "bac_jupyter_${USER}"
  #   tty: true
  #   env_file:
  #     - ../.env 

  # mlflow:
  #   build:
  #     context: .
  #   ports:
  #     - "127.0.0.1::5000"
  #   volumes:
  #      #- ../:/mnt
  #      - ../:/ka_azumio
  #   entrypoint: bash -c "mlflow server -h 0.0.0.0 --backend-store-uri ${MLFLOW_TRACKING_URI} --default-artifact-root ${MLFLOW_ARTIFACT_LOCATION:-'None'} -p 5000 && /bin/bash" 
  #   stdin_open: true
  #   container_name: "bac_mlflow_${USER}"
  #   tty: true
  #   env_file:
  #     - ../.env 
