version: '3'
services:

  jupyter:
    build:
      context: .
    ports:
       - "127.0.0.1::8888"
    volumes:
       - ../:/mnt
    entrypoint: bash -c "cd /mnt && jupyter lab --NotebookApp.token='' --ip=0.0.0.0 --allow-root && /bin/bash" 
    stdin_open: true
    container_name: "bac_jupyter_${USER}"
    tty: true
    env_file:
      - ../.env 

  mlflow:
    build:
      context: .
    ports:
      - "127.0.0.1::5000"
    volumes:
       - ../:/mnt
    entrypoint: bash -c "mlflow server -h 0.0.0.0 --backend-store-uri ${MLFLOW_TRACKING_URI} --default-artifact-root ${MLFLOW_ARTIFACT_LOCATION:-'None'} -p 5000 && /bin/bash" 
    stdin_open: true
    container_name: "bac_mlflow_${USER}"
    tty: true
    env_file:
      - ../.env 

  bash:
    build:
      context: .
    volumes:
       - ../:/mnt
    entrypoint: "/bin/bash" 
    stdin_open: true
    container_name: "bac_bash_${USER}"
    tty: true
    env_file:
      - ../.env 
