features_to_drop: ['guess_number',
  'monitor2','monitor3',
  'monitor_yesno','monitor_measure','monitor_transport',
  'monitor_number','monitor_content',
  'n_prior_zips', 
  'note_length', 'has_note', 'drinks_count','photo_count',
  'bac_cumulative_range',
  'bac_last2','bac_last3','bac_last4','bac_last5', 
  'bac_avg_lag3','bac_avg_lag4','bac_avg_lag5',
  'dist_cumulative_range', 'dist_cumulative_min',
  'mv_death_rate_2012', 
  'pct_zip_rural', 'pop_zip_rural','pop_zip_all','pop_zip_urban',
  'official_number_margin', 'official_number_estimate', 'official_percent_margin', 
  'culture_id',
  'spm_number_estimate', 'spm_number_margin', 'spm_percent_estimate', 'spm_percent_margin', 
  'difference_number', 'statistically_significant_difference',
  'avg_heavy_drinking_black_non_hispanic', 'avg_heavy_drinking_hispanic', 
  'avg_heavy_drinking_multiracial_non_hispanic', 'avg_heavy_drinking_other_non_hispanic', 'avg_heavy_drinking_white_non_hispanic', 
  'sqrt_n_users_per_state','sq_n_users_per_state', 'sq_n_users_by_bac', 
  'n_adj_75q_bac','state_75q_bac_avg',
  'loser_state_code_le','winner_state_code_le','is_game','is_holiday',
  'sales_tax_per_gal_2014', 'gas_tax_per_gal_2014', 'cig_tax_per_20pack_2014', 
  'taxes']
