# Referred to as models_config in train.py
boosting_params:
  silent: False, 
  class_weight: "balanced"
  n_estimators: 89
  reg_alpha: .5
  reg_lambda: .5
    
fit_params:
  eval_metric: "auc"
  early_stopping_rounds: 5