name: Continuous Integration

on: [push]

jobs:
    test:
      runs-on: ubuntu-latest
      container:
        image: docker://manifold/orbyter-ml-dev:3.0
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Black
        run: black --check bac
      - name: Flake8 
        run: flake8 bac
      - name: Unit Tests
        run: |
          pip install -r docker/requirements.txt
          pytest bac
        env:
          MLFLOW_TRACKING_URI: /experiments
          MLFLOW_ARTIFACT_LOCATION: 